[versions]

# mflisar (to use local snapshots use "LOCAL-SNAPSHOT" as version)
kmp-parcelize =             "1.0.1"
kmpdevtools =               "6.2.1" # also update the version in the root settings.gradle.kts
democomposables =           "1.0.2"
cachefileprovider =         "1.0.0"

# kotlinx
kotlinx-coroutines = 	     "1.10.2"
kotlinx-json = 			     "1.9.0"
kotlinx-datetime =           "0.7.1"
kotlinx-io-core =            "0.8.2"

# compose
# --

# others
# --

[plugins]

# mflisar
kmpdevtools-buildplugin =               { id = "io.github.mflisar.kmpdevtools.plugins-build-gradle",    version.ref = "kmpdevtools" }

[libraries]

# mflisar
kmp-parcelize =                         { module = "io.github.mflisar.parcelize:library", 	            version.ref = "kmp-parcelize" }
kmpdevtools-core =                      { module = "io.github.mflisar.kmpdevtools:core",                version.ref = "kmpdevtools" }
democomposables =                       { module = "io.github.mflisar.democomposables:library",         version.ref = "democomposables" }
cachefileprovider =                     { module = "io.github.mflisar.cachefileprovider:library", 	    version.ref = "cachefileprovider" }

# kotlinx
kotlinx-coroutines-core =			    { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", 	version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json =	        { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", 	version.ref = "kotlinx-json" }
kotlinx-datetime =	                    { module = "org.jetbrains.kotlinx:kotlinx-datetime", 	        version.ref = "kotlinx-datetime" }
kotlinx-io-core =			            { module = "org.jetbrains.kotlinx:kotlinx-io-core", 		    version.ref = "kotlinx-io-core" }

# compose
# --

# others
# --